version: '3.8'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=WcGGWwqK8tnrVhgRTjtG
    ports:
      - "9200:9200"
    networks:
      - drosera
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - drosera


  ssh-honeypot:
      build:
        context: ./ssh
        dockerfile: Dockerfile
      container_name: ssh-honeypot
      ports:
        - "2222:2222"
      environment :
        - SSH_PORT=2222
      volumes:
        - honeypot-logs:/var/log
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
      restart: unless-stopped
      networks:
        - honeypot-net
      security_opt:
        - no-new-privileges:true
      cap_drop:
        - ALL
      user: "sshuser"
      depends_on:
        - elasticsearch  # Wait for ES to start

  filebeat:
    build:
      context: .
      dockerfile: filebeat

    volumes:
      - honeypot-logs:/var/log
    networks:
      - drosera
    depends_on:
      - ssh-honeypot
      - elasticsearch
      - kibana



networks:
  drosera:
    driver: bridge
  honeypot-net:
    driver: bridge

volumes:
  honeypot-logs:

  elasticsearch-data:
    driver: local
