filebeat.inputs:
  - type: filestream
    id: honeypot-filestream-1       

    enabled: true
    paths:
      - /var/log/honeypot.json
    json.keys_under_root: true
    json.add_error_key: true
    parsers:
      - ndjson:
          overwrite_keys: true

setup.ilm.enabled: false

setup.template.enabled: true
setup.template.name: "honeypot-template"
setup.template.pattern: "honeypot-logs-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "filebeat"
  password: "SDJwxcdq873OOO"
  index: "honeypot-logs-%{+yyyy.MM.dd}"
