FROM python:3.11-slim


WORKDIR /ssh


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV LOG_FILE=/var/log/honeypot.json

EXPOSE 2222

CMD ["python", "main.py"]
